version: "3"
services:
  server:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${SERVER_PORT}:3000
    environment:
      BCRYPT_SALT: ${BCRYPT_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5433
    depends_on:
      - migrate
  migrate:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    command: npm run db:init
    working_dir: /app/server
    environment:
      BCRYPT_SALT: ${BCRYPT_SALT}
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -q
        - -d
        - ${DB_DB_NAME}
        - -U
        - ${DB_USER}
      timeout: 45s
      interval: 10s
      retries: 10
  mariadb:
    image: mariadb:10.8
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: UTC+6
      MYSQL_DATABASE: nest_smartmart
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
volumes:
  postgres: ~
  mariadb:
